version: '3.8'

services:
  # Основное приложение
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - HOST=0.0.0.0
      - PORT=5000
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
    networks:
      - photo-hosting

  # Nginx для статических файлов и прокси
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./uploads:/var/www/uploads:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - photo-hosting

networks:
  photo-hosting:
    driver: bridge

volumes:
  uploads: